// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo_E73K2fhguILGntrP9Xam6vi2DYwHy8',
    appId: '1:1060545162251:web:1e4be96426e16c20d96b0e',
    messagingSenderId: '1060545162251',
    projectId: 'flutter-firestore-be4cf',
    authDomain: 'flutter-firestore-be4cf.firebaseapp.com',
    storageBucket: 'flutter-firestore-be4cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVxAPvb5PHsVAbLCtZYknxFI8i_oh39cw',
    appId: '1:1060545162251:android:dc1c5676d9b0e0b5d96b0e',
    messagingSenderId: '1060545162251',
    projectId: 'flutter-firestore-be4cf',
    storageBucket: 'flutter-firestore-be4cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAF7lbg5N2f5NFHaxdvF8ZtmQzySJOMT4',
    appId: '1:1060545162251:ios:af139d80eefd3daed96b0e',
    messagingSenderId: '1060545162251',
    projectId: 'flutter-firestore-be4cf',
    storageBucket: 'flutter-firestore-be4cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAF7lbg5N2f5NFHaxdvF8ZtmQzySJOMT4',
    appId: '1:1060545162251:ios:af139d80eefd3daed96b0e',
    messagingSenderId: '1060545162251',
    projectId: 'flutter-firestore-be4cf',
    storageBucket: 'flutter-firestore-be4cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo_E73K2fhguILGntrP9Xam6vi2DYwHy8',
    appId: '1:1060545162251:web:a6dca6b616ccb42cd96b0e',
    messagingSenderId: '1060545162251',
    projectId: 'flutter-firestore-be4cf',
    authDomain: 'flutter-firestore-be4cf.firebaseapp.com',
    storageBucket: 'flutter-firestore-be4cf.firebasestorage.app',
  );
}
